name: Run Container

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Run Docker container
        run: |
          docker run -d --name projeto-pld-container -p 0.0.0.0:8501:8501 ghcr.io/${{ github.repository_owner }}/projeto-pld:latest

      - name: Print container logs
        run: docker logs -f projeto-pld-container

      - name: Print access IP
        run: echo "Access the application at http://$(curl -s ifconfig.me):8501"

      - name: Keep container running
        run: sleep infinity

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
